# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::ListNode; end
module ::Node; end
module ::Test::Unit::TestCase; end
module ::TreeNode; end
module PQueue::Node; end
module Rake::DSL; end
